import express from "express";
import { addRequest, approveRequest, declineRequest, deleteUser, getAllRequests } from "../controller/request.js";
import { requireAdmin } from "../controller/passport-setup.js";
const requestRouter = express.Router();
requestRouter.post("/add-request", addRequest);
requestRouter.post("/approve-request", approveRequest);
requestRouter.delete("/decline-request", declineRequest);
requestRouter.delete("/delete-user/:id", requireAdmin, deleteUser);
requestRouter.get("/get-all-requests", getAllRequests);
export default requestRouter;